# Generated by Django 5.1.4 on 2025-01-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentorm",
            name="profile",
            field=models.ImageField(default=0, upload_to="pics"),
            preserve_default=False,
        ),
    ]
